version: '3.8'

services:
  python_app:
    build: .
    container_name: my_running_app
    restart: always
    ports:
       - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./data:/app/data